#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

$test_array = [10, 3, 5, 1, 100, 50, 4];



echo "AscendingSort Test";
$AscSort = new \Mybeard\StrategySorter\Context(new \Mybeard\StrategySorter\AscendingSort());
$AscArray = $AscSort->executeStrategy($test_array);
$DescSort = new \Mybeard\StrategySorter\Context(new \Mybeard\StrategySorter\DescendingSort());
$DescArray = $AscSort->executeStrategy($test_array);


var_dump($AscArray);
var_dump($DescArray);